import type { Metadata } from "next";
import "./globals.css";
import { Space_Grotesk } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-space-grotesk",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${spaceGrotesk.variable}`}>
      <body
        className={`${spaceGrotesk.className} bg-[radial-gradient(circle_at_50%_75%,#27272b,#18181b)] text-white min-h-screen flex flex-col items-center justify-center scrollbarmain`}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
